-- Esquema del Sprint 1 (HU-01 a HU-06): usuarios, categorías, eventos y logs

CREATE TABLE usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    correo        VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol           VARCHAR(20)  NOT NULL,
    creado_en     TIMESTAMP,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE categorias (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(50) NOT NULL UNIQUE,
    activo    BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP
);

CREATE TABLE eventos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR(150) NOT NULL,
    descripcion       TEXT,
    fecha_inicio      TIMESTAMP    NOT NULL,
    ubicacion         VARCHAR(150) NOT NULL,
    cupos_maximos     INTEGER      NOT NULL,
    cupos_disponibles INTEGER      NOT NULL,
    estado            VARCHAR(20)  NOT NULL,
    organizador_id    BIGINT       NOT NULL REFERENCES usuarios (id),
    creado_en         TIMESTAMP,
    categoria_id      BIGINT       REFERENCES categorias (id)
);

CREATE TABLE logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha      TIMESTAMP   NOT NULL,
    usuario_id BIGINT,
    accion     VARCHAR(50) NOT NULL,
    entidad    VARCHAR(50) NOT NULL,
    entidad_id BIGINT,
    resultado  VARCHAR(20) NOT NULL,
    motivo     TEXT
);